volumes:
  seaweed_data:
  postgres_data:

services:
  retrieval-service:
    build:
      context: .
      dockerfile: services/retrieval-service/Dockerfile
    env_file:
      - ./services/retrieval-service/.env
    ports:
      - "8001:8001"

  ingestion-service:
    build:
      context: .
      dockerfile: services/ingestion_service/Dockerfile
    env_file:
      - ./services/ingestion_service/.env
    ports:
     - "8002:8002"
  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    env_file:
      - ./services/orchestrator/.env
    ports:
      - "8003:8003"
    depends_on:
      - postgres
  
  seaweedfs:
    image: chrislusf/seaweedfs
    command: server -s3 -s3.port=8333 -dir=/data
    ports:
      - "8333:8333"
      - "9333:9333"
    volumes:
      - seaweed_data:/data
  api-gateway:
    build: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - orchestrator
      - seaweedfs
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_BASE_URL: http://localhost:3000
    ports:
      - "80:80"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-gateway_db}
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 