apiVersion: apps/v1
kind: Deployment
metadata:
  name: retieval-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retieval-service
  template:
    metadata:
      labels:
        app: retrieval-service
    spec:
      containers:
        - name: retrieval-service
          image: 635668539225.dkr.ecr.ap-south-1.amazonaws.com/retrieval-service:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: retrieval-service-env
---
apiVersion: v1
kind: Service
metdata:
  name: retrieval-service
spec:
  selector:
    app: retrieval-service
  ports:
    - port: 8001
      targetPort: 8001